<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>splash_dot_index_4</name>
   <tag></tag>
   <elementGuidId>ac742b6c-50dc-4645-91a7-28bccb6c0a82</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>(//android.widget.ImageView[@resource-id='id.co.fundtastic.client:id/spring_dot'])[4]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>(//android.widget.ImageView[@resource-id='id.co.fundtastic.client:id/spring_dot'])[4]</value>
   </webElementProperties>
</WebElementEntity>
