<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_verifikasi_otp</name>
   <tag></tag>
   <elementGuidId>aab8f906-5236-491e-a8ec-2701bb12158f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//android.widget.TextView[@resource-id='id.co.fundtastic.client:id/btnVerified']
</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//android.widget.TextView[@resource-id='id.co.fundtastic.client:id/btnVerified']
</value>
   </webElementProperties>
</WebElementEntity>
