<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_otp</name>
   <tag></tag>
   <elementGuidId>5928b3cd-18a2-4113-a02e-fbeb4f8429f2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//android.widget.EditText[@resource-id='id.co.fundtastic.client:id/et_otp']
</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//android.widget.EditText[@resource-id='id.co.fundtastic.client:id/et_otp']
</value>
   </webElementProperties>
</WebElementEntity>
